version: "3.8"
services:
  mysql:
    image: mysql:5.7
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
  shopware:
    image: shyim/shopware:6.2.0
    build:
      context: .
    environment:
      APP_SECRET: 440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      INSTANCE_ID: 10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      APP_URL: http://localhost
      MAILER_URL: null://localhost
      DATABASE_HOST: mysql
      DATABASE_URL: mysql://shopware:shopware@mysql:3306/shopware
      SHOPWARE_ES_HOSTS: 
      SHOPWARE_ES_ENABLED: 0
      SHOPWARE_ES_INDEXING_ENABLED: 0
      SHOPWARE_ES_INDEX_PREFIX: 
      COMPOSER_HOME: /tmp/composer
      SHOPWARE_HTTP_CACHE_ENABLED: 1
      SHOPWARE_HTTP_DEFAULT_TTL: 7200
      INSTALL_LOCALE: de-DE
    ports:
      - 80:80