framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        pools:
            serializer:
                adapter: cache.adapter.redis
            annotations:
                adapter: cache.adapter.redis
            property_info:
                adapter: cache.adapter.redis
            messenger:
                adapter: cache.adapter.redis
            property_access:
                adapter: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_CACHE_HOST)%:%env(REDIS_CACHE_PORT)%/%env(REDIS_CACHE_DATABASE)%"