name: Build PHP
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/php.yml"
      - "rootfs/**"
jobs:
  php74:
    name: PHP 7.4
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
    
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build PHP
        run: docker buildx build -f ./php/7.4/Dockerfile --platform linux/amd64,linux/arm64 --tag ghcr.io/shyim/shopware-php:7.4 --tag ghcr.io/shyim/shopware-php:7.4.29 --push .
  php80:
    name: PHP 8.0
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
    
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build PHP
        run: docker buildx build -f ./php/8.0/Dockerfile --platform linux/amd64,linux/arm64 --tag ghcr.io/shyim/shopware-php:8.0 --tag ghcr.io/shyim/shopware-php:8.0.19 --push .
  php81:
    name: PHP 8.1
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
    
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build PHP
        run: docker buildx build -f ./php/8.1/Dockerfile --platform linux/amd64,linux/arm64 --tag ghcr.io/shyim/shopware-php:8.1 --tag ghcr.io/shyim/shopware-php:8.1.6 --push .